#!/usr/bin/env bash
#Display header
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
#Use ps command to display processes
ps aux --forest | head -50 | awk '{print $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11}'
