#!/usr/bin/env bash
#Get the PIDs of processes containing the word "bash"
pids=$(pgrep -l bash | awk '{print $1}')
#Iterate through PIDs and display PID along with process name
for pid in $pids; do
  name=$(ps -o comm= -p "$pid")
  echo "$pid $name"
done
