#!/usr/bin/env bash
#Find the process ID (PID) of the 7-highlander script
PID=$(pgrep -f "7-highlander")

if [ -z "$PID" ]; then
    echo "Process not found"
else
    # Use kill to terminate the process
    kill "$PID"
    echo "Killed"
fi
