#!/usr/bin/env bash

# This script is displaying "Best School" 10 times and says "Hi" on the 9th iteration

counter=0

while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]; then
        echo -n "Best School"
        echo -e "\nHi"
    else
        echo "Best School"
    fi
    ((counter++))
done
