#!/bin/bash

# Update the /etc/hosts file
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
sudo bash -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'

# Restart the networking service
sudo service networking restart

# Clear the DNS cache
sudo systemd-resolve --flush-caches
